### PR TITLE
add an _audio setup_ notice to setup so users flood our issues/gitter less

### PR DESCRIPTION
**Pull request by renekliment**
What the title says.
Maybe I should have PRed against `master`, but let's do this in `dev` and put extra pressure to roll out `v1.4` soon.

**Checklist:**
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/team Does not regard this issue, but I'd like to advertise that I'm thinking about introducing a _14-day PR merge rule_ so that when there is an open PR with no _blocking_ objections for at least 14 days, it can be merged without explicit approval of other team members. 
It's perfectly understandable that people don't have time to devote to AlexaPi to review stuff and I personally believe that if people with write access merge something even without a proper review, it will bring more good than harm to the project (keeps the development running, makes the project better as only people who have proved themselves have write access).

Feedback is, as always, welcome. If there are no objections, I'd like to start applying that rule as of Monday (the 6th of February). Cheers.

**Comment by dgonano** [comment]
@renekliment  I'm happy with the 14 day rule. I'm quite busy at the moment (finding new job & moving house) so I understand why it's required. 
I might just add though that "An attempt to contact relevant members should be made". I believe this rule is to account for people being busy, unavailable or unwilling rather than trying to sneak PRs through.

**Comment by renekliment** [comment]
@dgonano Ah yes, that's what I meant, but it didn't occur to me to write it. After doing the _team mention_ and no one saying anything blocking for two weeks, it would be free to merge.

**Comment by renekliment** [comment]
@dgonano Best of luck on doing these _life-related_ things. They can be quite stressful and time-consuming.

**Comment by dgonano** [comment]
thanks @renekliment, appreciated :)

**Comment by renekliment** [comment]
Thanks for the approval, merging.

**Pull request merged**
