### PR TITLE
Simple Snowboy support

### PR DESCRIPTION
**Pull request by renekliment**
**Issue this PR fixes (if applicable):** #53

**Description:**

What everybody has been waiting for. This _works_, there might be improvements later, but is _mergeable_.

The installation has to be done manually for now:

```bash
# Install snowboy dependencies as described in https://github.com/Kitt-AI/snowboy#ubunturaspberry-pipine64nvidia-jetson-tx1nvidia-jetson-tx2
# If you're on Raspbian < Stretch or you simply have older swig3.0, you need to install a newer than from the repo.
sudo apt-get install swig3.0 libatlas-base-dev

# install snowboy
sudo pip install git+https://github.com/Kitt-AI/snowboy.git
```

I think that's fine since it's experimental for now. Auto install should come in a later PR.

**Checklist:**
  - [ ] Update Wiki (new platform, installation, configuration changes etc)
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by pfiol** [comment]
Hi @renekliment I finally got time to test this one. It works perfectly on my RapsberryPi B+. Great work! :)

However, I've noticed that it is quite slow when collecting the answers from amazon. Does it records your voice for a fixed amount of time or it detects the silence to proceed to launch the query to amazon? Any clue where this delay may come from?

**Comment by renekliment** [comment]
@pfiol Thanks for the testing! There is a VAD. Also, yesterday I've rebased it on `dev`, where there is now a huge change to stream audio to AVS, instead of recording it all at once. Post your log in debug mode (w/o pocketsphinx stuff).

**Comment by pfiol** [comment]
@renekliment Yeah! I was about to comment again, just found the #44 issue. I think that's exactly what I was looking for. I will try it this afternoon. That's the only missing piece of the puzzle for me.

I've named my alexapi as "R2D2", replaced the "yes" and "hello" mp3 files for R2d2 sounds, and put everything inside a R2D2-like kitchen jar! hahaha it's awesome! :)

I will let you know my findings on the new code.

**Comment by pfiol** [comment]
Hi @renekliment 
I have locally merged this PR with the Master branch, to take benefit of the new voice "streaming" to amazon, and also use the snowboy trigger, and it works.

The only problem I found is that I have to wait around 2-3 seconds after it says "yes" to start making the question, Do you have any idea why there's such a delay and how to fix it?

**Comment by pfiol** [comment]
Just in case it someone tried to merge this PR with the master branch. I'm facing some delays after wake word detection. See the logs below:

```
2017-03-23 21:55:17 DEBUG: Keyword 1 detected
2017-03-23 21:55:17 DEBUG: Stopping audio play
2017-03-23 21:55:17 DEBUG: Stopped play. [Errno 3] No such process
2017-03-23 21:55:17 DEBUG: Playing audio: /opt/AlexaPi/src/resources/alexayes.mp3
2017-03-23 21:55:17 DEBUG: Started play. sox -q /opt/AlexaPi/src/resources/alexayes.mp3 -t alsa vol -2 dB pad 0 0
2017-03-23 21:55:19 DEBUG: Finished play. 
2017-03-23 21:55:19 DEBUG: Setting up recording
2017-03-23 21:55:19 DEBUG: Start recording
2017-03-23 21:55:19 DEBUG: Starting new HTTPS connection (1): access-alexa-na.amazon.com
2017-03-23 21:55:20 DEBUG: Start sending speech to Alexa Voice Service
2017-03-23 21:55:24 DEBUG: End recording
2017-03-23 21:55:24 DEBUG: Finished sending speech to Alexa Voice Service
2017-03-23 21:55:25 DEBUG: Processing Request Response...
```

It looks like it takes a lot of time to finish the "alexayes.mp3" and later again it takes a second or two to actually start sending/streaming the request to amazon. Afterwards everything goes fine, the reply from amazon is very fast.

Any idea?

**Comment by pfiol** [comment]
@renekliment I finally got all the pieces together for my personal project. I modified a little bit the code on this branch and used a customised wakeup word. This is the result: https://www.youtube.com/watch?v=E2xg2_iwZv4 

I hope you like it!

**Comment by probststefan** [comment]
Will this pull request be merged in the near future?

**Comment by renekliment** [comment]
@probststefan Well, I might have some time for AlexaPi again, so, it might. Snowboy can now be installed with `pip` (https://github.com/Kitt-AI/snowboy/issues/73), which should solve some of the tasks in the description.

To avoid something that very few people want, I ask: Do you people still want this?

**Comment by dapetcu21** [comment]
I support this and think would be useful. Without snowboy, AlexaPi is unusable for me.

**Comment by joe248** [comment]
I've been waiting and hoping for this as well.

**Comment by shreyasubale** [comment]
Same here, for me pocketsphinx almost never works properly ( accent ) and snowboy does well.

**Comment by revere521** [comment]
@renekliment I'd also like to have it...so yes please :)

**Comment by ezar** [comment]
+1

**Comment by ezar** [comment]
+1

**Comment by ezar** [comment]
Please add to master!!

**Comment by ezar** [comment]
Please commit :)

https://github.com/dolanmiu/MMM-awesome-alexa

**Comment by EmerickH** [comment]
You should rebase your branch on the actual branch to solve conflicts.

**Comment by renekliment** [comment]
@EmerickH I know, dude. The PyAudio / alexapi.sound conflicts are not so easy to solve though. I wasn't able to find the time lately. Hopefully I will soon. This is my thing to do about AlexaPi that I still want to do.

**Comment by mengjiann** [comment]
+1

**Comment by renekliment** [comment]
I still wanna do this. Hopefully in a few weeks. Personally I am moving to https://github.com/MycroftAI/mycroft-core

**Comment by renekliment** [comment]
@alexa-pi/team and everybody here: So, this is happening. Snowboy, yay.

- The installation is manual for now. Should be easy on Raspbian. On Arch Linux, you have to install `atlas-lapack` from AUR which is a little tricky and I guess could take days on a Raspberry Pi. I will post that to wiki later. See the PR description.
- I'm having a little trouble with Travis CI, but I'll figure it out.
- Please test so this can be finally merged.

Thanks.

**Comment by revere521** [comment]
!!!! awesome - Thanks @renekliment!

i am running the pip install right now, do i need to git pull the current alexapi to activate it, or make any config changes?

**Comment by renekliment** [comment]
@revere521 You need to checkout this PR branch. For example like this: https://github.com/alexa-pi/AlexaPi/blob/master/CONTRIBUTING.md#if-you-want-to-check-out-someone-elses-branch-for-example-a-pull-request

There is a new section in the config. You can simply add it to your config and disable pocketsphinx and enable snowboy.

**Comment by revere521** [comment]
i had to manually grab the deb for the armhf version of swig3.0 - http://mirrordirector-mb.raspbian.org/raspbian/pool/main/s/swig/swig3.0_3.0.10-1.1_armhf.deb

the pip install kept failing...   i think travis.yml mentions the amd64.deb

not sure if that matters or not - mine is a raspbian based pi 3

**Comment by renekliment** [comment]
@revere521 Did you run the `apt` commands from the snowboy's README? I've put it in the PR description to be clear.

**Comment by revere521** [comment]
I did, but the raspbian version that installs from apt is 3.0.2, so i just read through your chnages in the .yml and did that stuff manually, just to be sure.  that seemed to be the only thing i had to do was fix the .deb

**Comment by renekliment** [comment]
@revere521 I see. What Raspbian version are you using?

**Comment by revere521** [comment]
sorry, i got tied up - im on Raspbian Jessie, should be whatever is the current vanilla - not stretch

**Comment by revere521** [comment]
thats the only difference i have, and i use the platform - magicmirror, because it is a magic mirror too - and it seems to be working nicely

**Comment by renekliment** [comment]
@revere521 Can you compare it with pocketsphinx in regard of reliability (note there is also a value you can tweak) and CPU usage?

**Comment by revere521** [comment]
sorry just got home -- CPU usage at idle is fine - i haven't had time to really put it through the paces yet.  The audio response was a bit choppy, but my internet throughput may be to blame.     One question, it does not seem to be respecting my custom wakeword - is that set someplace else?  I notice that the selection is specifically under pocketsphinx...

top

**Comment by renekliment** [comment]
@revere521 Dope.

I've added the info about that to the wiki, see https://github.com/alexa-pi/AlexaPi/wiki/Triggers#snowboy

In the future, there might be an intergration in AlexaPi that would allow to train a personal model right from AlexaPi via snowboy's API, but that's a matter of another PR. As the title suggests, this is a basic support.

**Comment by revere521** [comment]
cool, thanks!  it does seem better overall - and i don't want to seem unappreciative that you made this available, because i am.  

Its going to be some new learning and dialing in - but thats why we play with software like this :)

i'll see if there is a way to create a custom wake word/hotword .pmdl on the Pi and let you know what happens.

**Comment by renekliment** [comment]
@revere521 Preferably, store it in `/etc/opt/AlexaPi/`. It might get deleted on snowboy upgrade in your location.

**Comment by revere521** [comment]
thats not a bad point, but for some reason when i do that i get ERROR: Urlerror: [Errno 111] connection refused. errors in the log.   I may try to troubleshoot more later; but weirdness.....

**Comment by renekliment** [comment]
@revere521 That particular error is probably related to MagicMirror. I'll make the log message more clear soon.

**Comment by revere521** [comment]
It does seem like its an inability to communicate with the listener for the plugin for the magic mirror; but it goes away when i put the umdl in the distribution folder - or at least thats what i observed

**Comment by revere521** [comment]
Been using it for a few days, works very well and after setting the sensitivity to 0.4 -  no false responses have occurred that i am aware of

absolutely fantastic

**Comment by renekliment** [comment]
So it's been 20 days since I've posted this. It's not ideal, but it's _mergeable_. I'm probably keeping the label _experimental_, since it requires manual installation and the code could use improvements.

Anyways, merging to `dev`.

**Comment by michibuddha** [comment]
I am  a quite noob to all this but I just built my RPi echo will it resolve the 5 to 10 sec delay I have after asking question??

**Pull request merged**
