### PR TITLE
bump requirements & install build-essential

### PR DESCRIPTION
**Pull request by renekliment**
**Issue this PR fixes (if applicable):** #185

**Description:**
- Installs `build-essential`, because some pypi packages need compiling.
- Fixes error when CherryPy==4.0.0 is installed that doesn't have `cheroot` as a requirement.
- Updates `requests` from old old version.
- Bumps patch versions of `pyalsaaudio`, `webrtcvad` - this should be only bugfixes, so no issue here.
- PR against `dev` as this should be tested a bit by someone else than me and I don't want to do a release just because of this - let's do a release with this and the AVS audio streaming. We can do a release tomorrow if this and the streaming get tested.

**Checklist:**
  - [x] Update CHANGELOG.md
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/team Please test, I'd like to release this _fix_ this weekend with the AVS streaming. Thank you.

**Comment by frisco82** [comment]
Now it throws a new error when it runs pip:

```
Leyendo la informaciÃ³n de estado... Hecho
libasound2-dev ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
build-essential ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
curl ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
git ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
libpulse-dev ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
python-dev ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
python-pip ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
python-setuptools ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
libsox-fmt-mp3 ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
sox ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
swig ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
vlc-nox ya estÃ¡ en su versiÃ³n mÃ¡s reciente.
0 actualizados, 0 nuevos se instalarÃ¡n, 0 para eliminar y 0 no actualizados.
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

```

**Comment by renekliment** [comment]
@frisco82 Please test now.

**Comment by frisco82** [comment]
The install is working now and it did finish the authorization.
I need to fix the mic configuration as default is not working to test everything, but the installation is working for me.

**Comment by renekliment** [comment]
@frisco82 Awesome, great to hear that!

**Comment by maso27** [comment]
I have installed this and verify that it is working as well.
As reported by @frisco82 the mic configuration took some work.  One of two things was necessary:

1.) change _allow_unlisted_input_device_ to _true_
or
2.) copy the exact line listed from the error message into it: _default:CARD=Device_ instead of just _default_

Considering this is intended to "just work" on a Raspberry Pi, I'd like to recommend changing the config.template.yaml to reflect one of those two scenarios.

Otherwise, thumbs up!

**Comment by renekliment** [comment]
@maso27 Dope, merging!

What do you mean _one of_? Is the device is in the list, you don't need to allow ... Please post the list and your portion of the config. Thank you.

**Comment by maso27** [comment]
Sorry, I'm away from the computer now, but what I mean is that config.yaml says "default" as the input device.  However, the app fails if you leave it set like that. You have to expand the definition to what I wrote above.
Or, you can get past it by enabling _allow_unlisted_input_device_.
But the app is being too restrictive so it will error out without adjustment from the default.

**Comment by maso27** [comment]
Still unrelated to this PR, but in order to expand on the above, here's what I get when I start main.py out of the box on a rPi2:

```
2017-03-05 04:14:04 CRITICAL: Your input_device 'default' is invalid. Use one of the following:
null
default:CARD=Device
sysdefault:CARD=Device
front:CARD=Device,DEV=0
surround21:CARD=Device,DEV=0
surround40:CARD=Device,DEV=0
surround41:CARD=Device,DEV=0
surround50:CARD=Device,DEV=0
surround51:CARD=Device,DEV=0
surround71:CARD=Device,DEV=0
iec958:CARD=Device,DEV=0
dmix:CARD=Device,DEV=0
dsnoop:CARD=Device,DEV=0
hw:CARD=Device,DEV=0
plughw:CARD=Device,DEV=0
```

I'm using a simple USB microphone and the 3.5mm jack for output.

**Comment by renekliment** [comment]
@maso27 Ah, I see. Well, it is nearly impossible to do it right due to the various audio HW out there. See #190 - hopefully that makes it better. Also, with #180, it's gonna change, so I wouldn't waste much time on this.

**Pull request merged**
