### PR TITLE
add PR template

### PR DESCRIPTION
**Pull request by dgonano**
Thank you for contributing to **AlexaPi**.

**Issue this PR fixes (if applicable):** #128 

**Description:**
Addes a PR template to pull requests

**Checklist:**
  - [x] Update CHANGELOG.md
  - [ ] Update Wiki (new platform, installation, configuration changes etc)
  - [x] PR Location (usually `master` for hotfixes, `dev` for general developmet)

### CODE REVIEW

**Comment by renekliment** [comment]
This is crazy - if you open a PR, I can just commit into that branch in your repo!
Anyway, I just wanted to try that. Thanks for this PR, merging.

**Comment by renekliment** [comment]
Yep, that's the only explanation that makes sense. That once you open a PR, you kinda offer it up to the public.

**Comment by ImEmJay** [comment]
Isn't that when you set the 'maintainer can edit' flag when you create the PR? Or is that only for the PR message?

**Comment by renekliment** [comment]
Yep, you're right: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Pull request merged**
