### PR TITLE
Fix calling unimported function in setup (dummy platform)

### PR DESCRIPTION
**Pull request by renekliment**
Silly thing. Doesn't fail install, but produces an ugly warning:

> `./AlexaPi/src/scripts/setup.sh: line 191: install_device_config: command not found`

TODO list:
- [x] mention this in the CHANGELOG! (part of this PR!)

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/coreteam Please test.

**Comment by dgonano** [comment]
This is a bug fix, i'd merge into `master` (not `dev`) and tag as `v1.3.1` to fix it as soon as possible.

**Comment by renekliment** [comment]
Ah, right, I need to get the hang of this. So, merge into `master`, tag and then merge `master` into `dev`? Locally and push or do it somehow via Pull Requests?

**Comment by renekliment** [comment]
Replaced by #123.

**Comment by renekliment** [comment]
Reopening, as I can actually just change the branch I want to merge into.

@lechat Seems like you can simply reopen your logging PR as well and change the branch to `master`. This way, we'll keep the comments and stuff.

@dgonano Do you approve of the PR itself then?

**Comment by dgonano** [comment]
yeah I have no issue with the fix, looks appropriate. Should update the CHANGELING to reflect the bug fix release if you're planning to tag it

**Comment by renekliment** [comment]
Ah, right! This will be a pretty much useless release, but let's do that for the practice :smile:

**Pull request merged**
