### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pfiol**
[AlexaPi.zip](https://github.com/alexa-pi/AlexaPi/files/800236/AlexaPi.zip)

Thank you for contributing to **AlexaPi**.

**Issue this PR fixes (if applicable):** #

**Description:**
  - [ ] This update add a new snowboy trigger.
**Checklist:**
  - [ ] Added snowboy files under "alexapi" folder and under "alexapi/triggers" folder.
  - [ ] Added some new settings on the config file on the trigger's setup area, to enable/disable snowboy.
  - [ ] it "works" but VERY choppy sound at my side...

### CODE REVIEW

**Comment by renekliment** [comment]
@pfiol Alright, let's move the discussion here.

Can you follow instructions so we make this a proper PR / do you know your way around git a bit?

**Comment by pfiol** [comment]
Hi,

To be honest, no I don't... I've just uploaded the ZIP file with all the code.

The only thing you should do is unzip it somewhere on your device, and run it. Consider that on the config.template.yaml  you will find the new parameters to enable the snowboy trigger.

**Comment by pfiol** [comment]
Hi,

Now I tried todo the following:

```
git checkout -b snowboy_trigger
M	src/config.template.yaml
M	src/main.py
Switched to a new branch 'snowboy_trigger'
```
And then:

```
git push origin snowboy_trigger
Username for 'https://github.com': pfiol
Password for 'https://pfiol@github.com': 
remote: Permission to alexa-pi/AlexaPi.git denied to pfiol.
fatal: unable to access 'https://github.com/alexa-pi/AlexaPi.git/': The requested URL returned error: 403
```
I followed this tutorial (https://yangsu.github.io/pull-request-tutorial/)  but it seems it's not working... sorry!

**Comment by renekliment** [comment]
@pfiol You need to push to your own fork (copy of the upstream repo). Click on the fork button to create your own pfiol/AlexaPi and then clone it via ssh.

**Comment by pfiol** [comment]
@renekliment yeah! :) 

There you go: https://github.com/pfiol/AlexaPi/tree/snowboy_trigger

**Comment by renekliment** [comment]
Ah, almost there :-)

First, checkout the `dev` branch, because that's what you want to base on:
`git checkout dev`

Create the branch for the thing - let's create a new _snowboy_ branch:
`git checkout -b snowboy`

Then, copy the changed files there (be sure not to overwrite the .git folder).

Prepare all the files for the commit:
`git add .`

Do the actual commit:
`git commit -m "snowboy support"`

And push:
`git push origin snowboy`

**Comment by pfiol** [comment]
Done: https://github.com/pfiol/AlexaPi/tree/snowboy

**Comment by renekliment** [comment]
Great! One last thing before we can start commenting on the work itself is to replay the changes on the current `dev`:

`git checkout snowboy` (you should be there already)
`git rebase dev`
`git push --force origin snowboy`

And then open a PR from your snowboy branch into our `dev` branch. 

Thanks!

**Comment by renekliment** [comment]
Closing this and we can discuss in the new PR.

**Pull request closed without merging**
