### PR TITLE
snowboy support

### PR DESCRIPTION
**Pull request by pfiol**
Thank you for contributing to **AlexaPi**.

**Issue this PR fixes (if applicable):** #

**Description:**

**Checklist:**
  - [ ] Update CHANGELOG.md
  - [ ] Update Wiki (new platform, installation, configuration changes etc)
  - [ ] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by pfiol** [comment]
I havethe feeling that some sort of signaling to capture and release of the audio devices will be needed. 

When I launch the app, most of the times I hear "hello" twice, I don't know why...

**Comment by pfiol** [comment]
Today I did some improvements with sound problems.

Fixed the pulseaudio according to the wiki, restored the snowboydecoder.py its original state, and put back the voice_confirm on main.py. Sound quality is much better now, but still not perfect. 

Alexa's "hello" is only being heard from time to time not every time I start the app.

**Comment by renekliment** [comment]
@pfiol Okay, I think I finally found a way to fixup your branch to be on the latest dev:
```
git cherry-pick b7366febfa25fdcb018da50220b67257533680b7
git cherry-pick e2e8caa4f11ecf30b835c89946db28d95d601256
git cherry-pick 0fdf5a8cc15bcbc38fa64c3f515e016740cdfe7d
git cherry-pick 7690d408bd8fe49938896e9147b81fc79b4a62d4
git push origin snowboy
```

**Comment by pfiol** [comment]
Done! :)

**Comment by renekliment** [comment]
Thanks!

I've thought about further progress and I think it would be much faster and beneficial if I implement it myself as described in #53. The good approach is a bit more complicated than I thought. Anyways, I gave it a shot and I have a working implementation. I'll share it soon.

I hope that's fine with you. I'm glad you've tested it and this way, it will get merged sooner, because we want to make sure it runs on all the supported devices if possible.

**Comment by renekliment** [comment]
@pfiol See #177 for details.

**Comment by pfiol** [comment]
Hi @renekliment 

Thank you for all the effort. I'm glad that at least I got the ball rolling for this feature, although my code was not used in the end :) 

However I will follow the progress so I can learn something out of this. Thank you for all the patience you showed to me when trying to teach me the github basics. I appreciate that.

Regards

**Pull request closed without merging**
