### PR TITLE
Check all sh files with shellcheck again

### PR DESCRIPTION
**Pull request by renekliment**
**Description:**
Forgot to change this with #141.

**Checklist:**
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/team I've got a couple of really small PRs. Please have a look. Thank you.

**Comment by enclarify** [comment]
This looks correct

**Comment by lechat** [comment]
Дщщлы пщщв

**Comment by renekliment** [comment]
Thanks! Merging!

**Pull request merged**
