### PR TITLE
CONTRIBUTING.md - written in details

### PR DESCRIPTION
**Pull request by renekliment**
Update so everyone knows what to do when they wanna send some code.

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/coreteam Please let me know if you agree with this.

**Comment by renekliment** [comment]
Did a little update. @alexa-pi/coreteam Let me know if it's okay like this and can be merged. Thank you.

**Comment by sammachin** [comment]
I'm happy with this.

Ok to merge

**Comment by renekliment** [comment]
Holy shit snacks @sammachin, that's a lot of comments from you this morning, I'm excited - I like this agile attitude! Merging!

**Pull request merged**
