### PR TITLE
stop the player on app exit, fixes #56

### LINKED ISSUE #56: Alexa gets messed up after Ctrl-C during playback
When playing back Tunein radio channels, I am not able to issue the Ctrl-C command. It also breaks voice detection thereafter.  Requires a Ctrl-Z and a kill -9. 

```
Sending Playback Progress Report Request...
Playback Progress Report was Successful!
```

### PR DESCRIPTION
**Pull request by renekliment**
Just a quick one-liner.

@alexa-pi/coreteam Please have a look, there should be no issues here. Thank you.

### CODE REVIEW

**Comment by maso27** [comment]
Good fix!
I can break it during "News Flash" without the fix, and can't with it.

Ready to merge.

**Comment by renekliment** [comment]
> I can break it during "News Flash" without the fix, and can't with it.

Just to be sure, by _break it_ you mean _break_ the app, right? So this fixes it.

**Comment by maso27** [comment]
Haha yeah sorry.
A little ambiguous there.
I could break AlexaPi before by typing "Ctrl-C" when the News Briefing was playing.  Got stuck, wouldn't exit.

I changed this line, and now "Ctrl-C" exits the app cleanly instead.

So this fixes it.

**Comment by renekliment** [comment]
Great, thanks :-) Merging then.

**Pull request merged**
