### PR TITLE
Fix current build errors

### PR DESCRIPTION
**Pull request by renekliment**
This is just a little thing before we do at least the basic CI for real. It fixes the few issues so the tests don't fail by default, which is annoying.

### CODE REVIEW

**Comment by renekliment** [comment]
Also, after this is merged, the tests have to pass for any PR to get merged.
We'll be adding some real tests later, but now we have at least the super basic _pylint_ stuff (`--errors-only`) as a sort of sanity check.

@alexa-pi/coreteam Please tell me, if this is okay.

**Comment by renekliment** [comment]
@alexa-pi/coreteam Please tell me if this is ok. It's a very small change, but it lets us start using CI, even though we'll have just very basics tests for now.

**Comment by maso27** [comment]
It's ok by me.

**Comment by renekliment** [comment]
Awesome, merging!

**Pull request merged**
