### PR TITLE
Fix unwanted variable expansion

### PR DESCRIPTION
**Pull request by renekliment**
**Description:**
- We should probably fix this in `master`, but meh, who cares, it's not a major issue. I still hope to roll out _v1.4_ soon.
- found by @maso27
- http://stackoverflow.com/questions/27920806/how-to-avoid-heredoc-expanding-variables

### CODE REVIEW

**Comment by lechat** [comment]
I don't think that this is major issue that have to be fixed in master. So far none of the users stumbled on it.

**Comment by renekliment** [comment]
Yep. It's a major problem in `dev`, since we have that strict mode that exists the script on non-existent variable.

**Comment by renekliment** [comment]
@alexa-pi/team Btw, if you guys feel that any of the open PRs can be merged, don't be shy to share :smile:

**Comment by dgonano** [comment]
im cherry picking all the easy PRs so some can be merged lol

**Comment by renekliment** [comment]
Thanks! In `dev` with it!

**Pull request merged**
