### PR TITLE
device_platforms: better file naming and directory structure

### PR DESCRIPTION
**Pull request by renekliment**
**Description:**
There should be noting problematic about this.
@alexa-pi/team Please let me know if this is okay, so I can merge it.

**Checklist:**
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by lechat** [comment]
looks good

**Comment by renekliment** [comment]
Okay to merge?

**Comment by renekliment** [comment]
Damn, the silly thumbs don't do notifications. Please do comments instead :-) Merging.

**Comment by maso27** [comment]
I think we'll just have to do it this way from now on:
```
      / )
     ' /
    ' (_____
---'    ((__)
        ((___)
        ((__)
----.___((_)
```

:-)

**Comment by renekliment** [comment]
:laughing:

**Pull request merged**
