### PR TITLE
Stream audio to AVS

### PR DESCRIPTION
**Pull request by renekliment**
**Issue this PR fixes (if applicable):** #44

**Description:**
- Brings huge speed improvement (response latency).
- This means that when your recording LED (or whatever your device equivalent) is on, data gets sent to Amazon already.
- Used code from @respeaker (thank you!).

**Checklist:**
  - [x] Update CHANGELOG.md
  - [x] PR Location (usually `master` for hotfixes, `dev` for general development)

### CODE REVIEW

**Comment by renekliment** [comment]
@alexa-pi/team Please test.

Tagging @gemx @lechat @illperipherals @dly9014

**Comment by sammachin** [comment]
@renekliment I've installed on my Pi3 here, had to change the `default` audio device but thats the same in all builds.
Starts up fine and wakeword or button trigger works but when it starts recording I get the following error:
```
2017-03-04 19:55:39 DEBUG: Button pressed!
2017-03-04 19:55:39 DEBUG: Setting up recording
2017-03-04 19:55:39 DEBUG: Start recording
2017-03-04 19:55:39 INFO: Starting new HTTPS connection (1): access-alexa-na.amazon.com
2017-03-04 19:55:40 DEBUG: Start sending speech to Alexa Voice Service
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./main.py", line 544, in trigger_process
    alexa_speech_recognizer(audio_stream)
  File "./main.py", line 347, in alexa_speech_recognizer
    resp = requests.post(url, headers=headers, data=data)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    low_conn.send(i)
  File "/usr/lib/python2.7/httplib.py", line 855, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
SysCallError: (-1, 'Unexpected EOF')
```

**Comment by renekliment** [comment]
@sammachin Damn! :-( Did you run the install script?

**Comment by renekliment** [comment]
The issue seems to be https://github.com/kennethreitz/requests/issues/2022 I'm not sure what is the solution exactly.

**Comment by sammachin** [comment]
@renekliment yep, cloned your branch, `git clone -b audio-streaming https://github.com/renekliment/AlexaPi.git` into `/opt/AlexaPi` I renamed the previous install folder as `AlexaPi1.4` then ran setup.sh and deleted then created a new config file from scratch. So not quite a completely fresh Pi install but I think that shouldn't be an issue?
I'm working on a train back from London so tethered to my phone over 4G, don't really want to try and build a new Pi image as well!

**Comment by renekliment** [comment]
@sammachin Yeah, that's correct install, that's fine.

Post your `pip list` please.

**Comment by sammachin** [comment]
ah ok will try #187 first,

**Comment by renekliment** [comment]
If that doesn't help, have a look at that link - there's many comments and one of them should solve it.

**Comment by sammachin** [comment]
Ok installed #187 which seemed to run fine, just did a couple of basic tests. 
Then went back and re-installed this build again with a brand new config file,

It starts up fine and seems to run nicely, wake word or button trigger and the vad looks good.
BUT
I mostly get back null responses from Alexa, out of 10 'what time is it' questions she only gave me the time twice

**Comment by renekliment** [comment]
@sammachin Alright, can you paste the logs (full) when running in debug mode when you get null response? Also, check / upload your `recording.wav`.

**Comment by sammachin** [comment]
@renekliment where is the recording.wav kept these days? I thought it was /tmp?

**Comment by renekliment** [comment]
@sammachin It's `/tmp/AlexaPi-runtime-something`.

**Comment by sammachin** [comment]
OK got the recording.wav, its not really a wav file anymore but I guess thats its now raw pcm data which is almost the same thing (wav files have a short header) and AVS is happy with either.
I tried importing it through audacity which can read raw pcm audio set the params as L16PCM 16Khz but the file is just noise.
[recording.wav.zip](https://github.com/alexa-pi/AlexaPi/files/818930/recording.wav.zip)
(had to zip file to upload to GH)

**Comment by renekliment** [comment]
@sammachin You can `aplay -r 16000 -f S16_LE recording.wav`, which works for my recordings, but gives me an awful noise on yours ... hmmm ...

**Comment by renekliment** [comment]
@sammachin Does _v1.4_ work on the same setup?

**Comment by sammachin** [comment]
Yep 1.4 and the build from 187 are both fine, I've had to pack up now as my
train is arriving but I should have some more time tmw eve

**Comment by renekliment** [comment]
I'm thinking, since you tested #187, you got new versions of dependencies ... Can you test _v1.4_ now to make sure it works with those and then test this again?

**Comment by maso27** [comment]
I'm testing this as well, on a rPi 2, and I'm not seeing any errors but am getting a lot of "Request Response is null (This is OKAY!)" responses to my requests.

She has responded to two of my requests (not the first one, but a couple seemingly at random during my testing) and the other 20 or so have been dropped on the floor.

**Comment by illperipherals** [comment]
Are you all using SoX as the playback handler?

**Comment by renekliment** [comment]
@maso27 Okay, I'll debug more.

@illperipherals Playback handler is not related to this.

**Comment by renekliment** [comment]
It seems like I can reproduce it on my Orange Pi (it works fine on my laptop). I'll get back to you guys.

**Comment by renekliment** [comment]
@maso27 @illperipherals Can you guys also upload your `recording.wav`? (ideally a couple of them) ... and the logs.

**Comment by gemx** [comment]
I experience the same problems. Wakewords works but after that always the null response. No error in the log. Using a raspi 3 and using your branch from your fork

**Comment by renekliment** [comment]
Are you guys using PulseAudio? Not that it should matter.
Also, upload your recordings please.

**Comment by gemx** [comment]
My setup:
* Raspi 3
* Seperate USB Soundcard with 3.5mm jack microphone
* Loudspeaker attached to 3.5mm jack of raspi
* NOT using pulseaudio
* using VLC playback handler
* fresh install of your fork and branch

Scenario:
* Asking "Wie spät ist es" (german for: What's the current time)

Result:
Works 1-2 times out of 10 attempts randomly

Attached are 2 zips

"not working" contains the mp3 of one successfull attempt and the recording wav of the last failed attempt as well as the full log

"working" contains the recording.wav where it worked and the resulting mp3 answer.

Hope that helps
[not working.zip](https://github.com/alexa-pi/AlexaPi/files/822234/not.working.zip)
[working.zip](https://github.com/alexa-pi/AlexaPi/files/822233/working.zip)

**Comment by friscoMad** [comment]
> osmc@osmc:/opt/AlexaPi$ sudo /opt/AlexaPi/src/main.py -d
> INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/feat.params
> Current configuration:
> [NAME]    [DEFLT]  [VALUE]
> -agc      none  none
> -agcthresh  2.0  2.000000e+00
> -allphone
> -allphone_ci  no  no
> -alpha    0.97  9.700000e-01
> -ascale   20.0  2.000000e+01
> -aw       1  1
> -backtrace  no  no
> -beam     1e-48  1.000000e-48
> -bestpath  yes  yes
> -bestpathlw  9.5  9.500000e+00
> -ceplen   13  13
> -cmn      live  batch
> -cmninit  40,3,-1  41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
> -compallsen  no  no
> -debug      0
> -dict       /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
> -dictcase  no  no
> -dither   no  no
> -doublebw  no  no
> -ds       1  1
> -fdict
> -feat     1s_c_d_dd 1s_c_d_dd
> -featparams
> -fillprob  1e-8  1.000000e-08
> -frate    100  100
> -fsg
> -fsgusealtpron  yes  yes
> -fsgusefiller  yes  yes
> -fwdflat  yes  yes
> -fwdflatbeam  1e-64  1.000000e-64
> -fwdflatefwid  4  4
> -fwdflatlw  8.5  8.500000e+00
> -fwdflatsfwin  25  25
> -fwdflatwbeam  7e-29  7.000000e-29
> -fwdtree  yes  yes
> -hmm        /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us
> -input_endian  little  little
> -jsgf
> -keyphrase    alexa
> -kws
> -kws_delay  10  10
> -kws_plp  1e-1  1.000000e-01
> -kws_threshold  1  1.000000e-50
> -latsize  5000  5000
> -lda
> -ldadim   0  0
> -lifter   0  22
> -lm
> -lmctl
> -lmname
> -logbase  1.0001  1.000100e+00
> -logfn
> -logspec  no  no
> -lowerf   133.33334 1.300000e+02
> -lpbeam   1e-40  1.000000e-40
> -lponlybeam  7e-29  7.000000e-29
> -lw       6.5  6.500000e+00
> -maxhmmpf  30000  30000
> -maxwpf   -1  -1
> -mdef
> -mean
> -mfclogdir
> -min_endfr  0  0
> -mixw
> -mixwfloor  0.0000001 1.000000e-07
> -mllr
> -mmap     yes  yes
> -ncep     13  13
> -nfft     512  512
> -nfilt    40  25
> -nwpen    1.0  1.000000e+00
> -pbeam    1e-48  1.000000e-48
> -pip      1.0  1.000000e+00
> -pl_beam  1e-10  1.000000e-10
> -pl_pbeam  1e-10  1.000000e-10
> -pl_pip   1.0  1.000000e+00
> -pl_weight  3.0  3.000000e+00
> -pl_window  5  5
> -rawlogdir
> -remove_dc  no  no
> -remove_noise  yes  yes
> -remove_silence  yes  yes
> -round_filters  yes  yes
> -samprate  16000  1.600000e+04
> -seed     -1  -1
> -sendump
> -senlogdir
> -senmgau
> -silprob  0.005  5.000000e-03
> -smoothspec  no  no
> -svspec     0-12/13-25/26-38
> -tmat
> -tmatfloor  0.0001  1.000000e-04
> -topn     4  4
> -topn_beam  0  0
> -toprule
> -transform  legacy  dct
> -unit_area  yes  yes
> -upperf   6855.4976 6.800000e+03
> -uw       1.0  1.000000e+00
> -vad_postspeech  50  50
> -vad_prespeech  20  20
> -vad_startspeech 10  10
> -vad_threshold  2.0  2.000000e+00
> -var
> -varfloor  0.0001  1.000000e-04
> -varnorm  no  no
> -verbose  no  no
> -warp_params
> -warp_type  inverse_linear inverse_linear
> -wbeam    7e-29  7.000000e-29
> -wip      0.65  6.500000e-01
> -wlen     0.025625 2.562500e-02
> 
> INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
> INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
> INFO: mdef.c(518): Reading model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
> INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
> INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/mdef
> INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
> INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/transition_matrices
> INFO: acmod.c(117): Attempting to use PTM computation module
> INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/means
> INFO: ms_gauden.c(242): 42 codebook, 3 feature, size:
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/variances
> INFO: ms_gauden.c(242): 42 codebook, 3 feature, size:
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(244):  128x13
> INFO: ms_gauden.c(304): 222 variance values floored
> INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/sendump
> INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
> INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
> INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
> INFO: ptm_mgau.c(838): Maximum top-N: 4
> INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
> INFO: dict.c(320): Allocating 138824 * 20 bytes (2711 KiB) for word entries
> INFO: dict.c(333): Reading main dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/cmudict-en-us.dict
> INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
> INFO: dict.c(336): 134723 words read
> INFO: dict.c(358): Reading filler dictionary: /usr/local/lib/python2.7/dist-packages/pocketsphinx/model/en-us/noisedict
> INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
> INFO: dict.c(361): 5 words read
> INFO: dict2pid.c(396): Building PID tables for dictionary
> INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
> INFO: dict2pid.c(132): Allocated 21336 bytes (20 KiB) for word-final triphones
> INFO: dict2pid.c(196): Allocated 21336 bytes (20 KiB) for single-phone word triphones
> INFO: kws_search.c(406): KWS(beam: -1080, plp: -23, default threshold -1125, delay 10)
> 2017-03-06 20:21:44 DEBUG: Setting up playback handler: VlcHandler
> 2017-03-06 20:21:44 INFO: Checking Internet Connection ...
> 2017-03-06 20:21:44 DEBUG: Starting new HTTPS connection (1): api.amazon.com
> 2017-03-06 20:21:45 DEBUG: https://api.amazon.com:443 "GET /auth/o2/token HTTP/1.1" 404 29
> 2017-03-06 20:21:45 INFO: Connection OK
> 2017-03-06 20:21:45 INFO: AVS token: Requesting a new one
> 2017-03-06 20:21:45 DEBUG: Starting new HTTPS connection (1): api.amazon.com
> 2017-03-06 20:21:46 DEBUG: https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 200 980
> 2017-03-06 20:21:46 INFO: AVS token: Obtained successfully
> 2017-03-06 20:21:46 DEBUG: Stopping audio play
> 2017-03-06 20:21:46 DEBUG: Playing audio: /opt/AlexaPi/src/resources/hello.mp3
> 2017-03-06 20:21:46 DEBUG: Player State: State.Opening
> 2017-03-06 20:21:47 DEBUG: Player State: State.Playing
> 2017-03-06 20:21:47 DEBUG: Started play.
> 2017-03-06 20:21:50 DEBUG: Player State: State.Ended
> 2017-03-06 20:21:50 DEBUG: Finished play.
> INFO: cmn_live.c(120): Update from < 41.00 -5.29 -0.12  5.09  2.48 -4.07 -1.37 -1.78 -5.08 -2.05 -6.45 -1.42  1.17 >
> INFO: cmn_live.c(138): Update to   < 30.77  3.22 -12.78 -6.04 -3.26  1.04 -6.34  5.34  1.77  9.79 -0.81 -4.17 11.37 >
> INFO: kws_search.c(656): kws 4.70 CPU 0.992 xRT
> INFO: kws_search.c(658): kws 35.69 wall 7.530 xRT
> 2017-03-06 20:22:22 DEBUG: Stopping audio play
> 2017-03-06 20:22:22 DEBUG: Playing audio: /opt/AlexaPi/src/resources/alexayes.mp3
> 2017-03-06 20:22:22 DEBUG: Player State: State.Opening
> 2017-03-06 20:22:22 DEBUG: Player State: State.Playing
> 2017-03-06 20:22:22 DEBUG: Started play.
> 2017-03-06 20:22:22 DEBUG: Player State: State.Ended
> 2017-03-06 20:22:22 DEBUG: Finished play.
> 2017-03-06 20:22:22 DEBUG: Setting up recording
> 2017-03-06 20:22:22 DEBUG: Start recording
> 2017-03-06 20:22:22 DEBUG: Starting new HTTPS connection (1): access-alexa-na.amazon.com
> 2017-03-06 20:22:23 DEBUG: Start sending speech to Alexa Voice Service
> 2017-03-06 20:22:24 DEBUG: End recording
> 2017-03-06 20:22:24 DEBUG: Finished sending speech to Alexa Voice Service
> 2017-03-06 20:22:24 DEBUG: Processing Request Response...
> 2017-03-06 20:22:24 DEBUG: Request Response is null (This is OKAY!)
> 

My setup is a Raspi 2, using osmc, dev with pull 187 and this, I did a setup after pulling this to update latest requirementes.

I think I have attached my not  working audio test, else I will update right now.

**Comment by sammachin** [comment]
@renekliment to answer your question about going back to 1.4 on the device thats now running this build, I just swapped the dir and yes 1.4 still works fine on here

**Comment by renekliment** [comment]
Thank you for your reports, guys!

Not that I think it should work now (I don't see a reason why it hasn't been working), but please try now.

**Comment by sammachin** [comment]
ok that latest version seems to work a lot better 8/8 'what time is it' tests worked, I'm not sure its any faster though, but thats probably down to be having a 20mb upload here, I'll try and throttle the connection on my router to test again :)

**Comment by renekliment** [comment]
@sammachin Post the log on this.

**Comment by renekliment** [comment]
@sammachin And make sure you're not using another branch accidentally :smile:

**Comment by gemx** [comment]
Works great for me :-)

**Comment by renekliment** [comment]
@gemx Glad to hear that!

Post your logs guys so we can see the timings and stuff (without the pocketsphinx crap please).

**Comment by gemx** [comment]
Here is my log 
[avs-stream-working.txt](https://github.com/alexa-pi/AlexaPi/files/822524/avs-stream-working.txt)

**Comment by sammachin** [comment]
ah yeah looks like the older branch was still running even though I'd
swapped folders, yes much faster too,

10 'what time is it' tests all pass

 I've throttled both pi's to 64k upload and the difference is 4sec vs 14
sec of 'processing' time, I'll try and record a video that demonstrates it
nicely :)

**Comment by renekliment** [comment]
Dope! In noisy environments, it can still take some time till VAD stops recording (nothing changed there), but after that happens, the rest should be instant.

**Comment by renekliment** [comment]
Let me guys now when you think this is merge-ready. Thank you!

**Comment by sammachin** [comment]
```
2017-03-06 21:09:52 DEBUG: Setting up recording
2017-03-06 21:09:52 DEBUG: Button pressed!
2017-03-06 21:09:52 DEBUG: Start recording
2017-03-06 21:09:52 DEBUG: Starting new HTTPS connection (1): access-alexa-na.amazon.com
2017-03-06 21:09:53 DEBUG: Start sending speech to Alexa Voice Service
2017-03-06 21:09:54 DEBUG: Button released.
2017-03-06 21:09:54 DEBUG: End recording
2017-03-06 21:09:54 DEBUG: Finished sending speech to Alexa Voice Service
2017-03-06 21:09:55 DEBUG: Button pressed!
2017-03-06 21:09:55 DEBUG: Button released.
2017-03-06 21:10:00 DEBUG: Processing Request Response...
2017-03-06 21:10:00 DEBUG: JSON String Returned: {
  "messageBody": {
    "directives": [
      {
        "namespace": "Speaker", 
        "name": "SetMute", 
        "payload": {
          "mute": false
        }
      }, 
      {
        "namespace": "SpeechSynthesizer", 
        "name": "speak", 
        "payload": {
          "contentIdentifier": "amzn1.as-ct.v1.Domain:Application:Notifications#ACRI#DeviceTTSRenderer_fb49a635-f31b-47a0-9af3-be0c9f644c87", 
          "audioContent": "cid:DeviceTTSRenderer_fb49a635-f31b-47a0-9af3-be0c9f644c87_1350390777"
        }
      }
    ]
  }, 
  "messageHeader": {}
}
2017-03-06 21:10:00 DEBUG: Stopping audio play
2017-03-06 21:10:00 DEBUG: Playing audio: file:///tmp/AlexaPi-runtime-0O27V4/DeviceTTSRenderer_fb49a635-f31b-47a0-9af3-be0c9f644c87_1350390777.mp3
2017-03-06 21:10:00 DEBUG: Player State: State.Opening
2017-03-06 21:10:00 DEBUG: Player State: State.Playing
2017-03-06 21:10:00 DEBUG: Started play. 
2017-03-06 21:10:02 DEBUG: Player State: State.Ended
2017-03-06 21:10:02 DEBUG: Finished play. 
```

**Comment by renekliment** [comment]
@sammachin Is that the 64k upload? 6 seconds is a lot. I'm getting about 1 second processing on a 10 Mb/s upload.

**Comment by sammachin** [comment]
@renekliment I posted a couple of videos comparing this with the 1.4 build, first time I had my router throttled to 64000bps upload which is actually slower than 'real time' 16bit 16kHz is 256kpbs however its a good test to see that the streaming code can cope with having to buffer the upload and its still twice as fast as 1.4
https://www.youtube.com/watch?v=0vuD8kO9kFM

I then changed the throttle to 300kpbs and tested again, sure enough thats almost instant 
https://www.youtube.com/watch?v=wpkjoHZHxnM

Final tests with the throttle removed so the full 20meg up seems to be about the same on this build the 1.4 runs faster than it did on 300k but thats to be expected.

Still not quite as fast as my Tap is but then I suspect there's additional improvements to be had by using the HTTP/2 api 

Good job! I think it could do with a bit more testing on different platforms and network connections before we merge, I can't really see that it will have any effect testing out different services/commands though?

**Comment by renekliment** [comment]
@sammachin Nice!

Yeah, that shouldn't matter.

If you agree (it works for @gemx also), I'd merge it into `dev`, since I can't think of any issues with this (well, I couldn't before and look how it worked out :smile:), leave it there for a day or two and then release as _v1.5_.

**Comment by gemx** [comment]
I am fine with merging :-)

**Comment by sammachin** [comment]
oh yeah by all means merge to dev 👍

**Comment by sammachin** [comment]
Once its in dev I'll run an install on a fresh raspbian card to make sure we haven't missed any deps.

**Comment by renekliment** [comment]
Dope, merging!

**Comment by sammachin** [comment]
FYI Just tested the dev branch on a completely fresh raspbian jessie lite card, all good

**Comment by renekliment** [comment]
@sammachin Great! Hopefully we'll have less regressions with the upcoming release than with the current :-)

**Pull request merged**
